window.HTML_APPS_PROJECTS = [
  {
    name: "Dose Response Pro",
    folder: "C:\\HTML apps\\dosehtml",
    path: "./dosehtml/dose-response-pro.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Dose-response meta-analysis in a single distributable HTML artifact with validation and CLI support alongside it.",
    note: "Canonical browser entry for the dose-response workspace.",
    tags: ["dose-response", "meta-analysis", "validated"]
  },
  {
    name: "TruthCert Pairwise Pro",
    folder: "C:\\HTML apps\\Truthcert1",
    path: "./Truthcert1/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pairwise meta-analysis workspace with a stable landing page, production HTML build, and paper package.",
    note: "Use the landing page to reach the production build without hunting through backup artifacts.",
    tags: ["pairwise", "truthcert", "meta-analysis"]
  },
  {
    name: "AdaptSim",
    folder: "C:\\AdaptSim",
    path: "../AdaptSim/index.html",
    collection: "existing",
    mode: "file",
    category: "Trial Design",
    summary: "Browser-based adaptive group-sequential trial simulator validated against rpact.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["adaptive-design", "group-sequential", "rpact"]
  },
  {
    name: "Al-Mizan",
    folder: "C:\\AlMizan",
    path: "../AlMizan/index.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Evidence equipoise monitor for cumulative meta-analysis, waste estimation, and tipping-point review.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["equipoise", "cumulative-meta-analysis", "tsa"]
  },
  {
    name: "CardioOracle",
    folder: "C:\\Models\\CardioOracle",
    path: "../Models/CardioOracle/index.html",
    collection: "existing",
    mode: "file",
    category: "Clinical Prediction",
    summary: "Browser-native cardiovascular trial outcome prediction tool with calibration, provenance, and training-data exploration.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["prediction", "clinicaltrials", "cardiology"]
  },
  {
    name: "CardioSynth Phase 0",
    folder: "C:\\cardiosynth",
    path: "../cardiosynth/phase0/colchicine-stemi.html",
    collection: "existing",
    mode: "file",
    category: "Living Meta-Analysis",
    summary: "Phase 0 living cardiology synthesis dashboard built from ClinicalTrials.gov structured results.",
    note: "This links directly to the current phase deliverable because the repo has no separate landing page yet.",
    tags: ["living-review", "cardiology", "ctgov"]
  },
  {
    name: "NICE Cardiology",
    folder: "C:\\NICECardiology",
    path: "../NICECardiology/index.html",
    collection: "existing",
    mode: "file",
    category: "Clinical Dashboard",
    summary: "Critical cardiology guideline review dashboard covering heart failure and acute coronary syndromes.",
    note: "Root-level project outside C:\\HTML apps, linked here for easier launch.",
    tags: ["guidelines", "cardiology", "dashboard"]
  },
  {
    name: "Focus Studio",
    folder: "C:\\HTML apps\\focus-studio",
    path: "./focus-studio/index.html",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "A polished focus timer with task tracking, session history, and local browser persistence.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["timer", "tasks", "localstorage"]
  },
  {
    name: "Kanban Lab",
    folder: "C:\\HTML apps\\kanban-lab",
    path: "./kanban-lab/index.html",
    collection: "new",
    mode: "file",
    category: "Productivity",
    summary: "Drag-and-drop planning board for quick project triage with persistent columns and card notes.",
    note: "Standalone productivity app stored in the workspace.",
    tags: ["kanban", "planning", "drag-and-drop"]
  },
  {
    name: "Evidence Board",
    folder: "C:\\HTML apps\\evidence-board",
    path: "./evidence-board/index.html",
    collection: "new",
    mode: "file",
    category: "Research Notes",
    summary: "Structured evidence note board with confidence labels, filtering, and JSON export/import.",
    note: "Standalone research-notes app stored in the workspace.",
    tags: ["research", "notes", "export"]
  },
  {
    name: "HTA Pro",
    folder: "C:\\HTML apps\\HTA",
    path: "./HTA/index.html",
    collection: "existing",
    mode: "file",
    category: "Health Technology Assessment",
    summary: "Browser-native Health Technology Assessment workspace covering cost-effectiveness, decision analysis, and benchmark comparisons against TreeAge.",
    note: "Large single-file app (7K+ lines) — opens directly from the file system.",
    tags: ["hta", "cost-effectiveness", "decision-analysis"]
  },
  {
    name: "IPD Meta-Pro",
    folder: "C:\\HTML apps\\IPD-Meta-Pro",
    path: "./IPD-Meta-Pro/ipd-meta-pro.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Individual Participant Data meta-analysis in a single distributable HTML artifact with PLOS ONE and F1000 submission packages.",
    note: "The real app is ipd-meta-pro.html; the index.html file is a thin stub.",
    tags: ["ipd", "meta-analysis", "individual-participant-data"]
  },
  {
    name: "Pairwise AI",
    folder: "C:\\HTML apps\\Pairwiseai",
    path: "./Pairwiseai/Main screen.html",
    collection: "existing",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pairwise meta-analysis AI variant with a dedicated main-screen entry, expert-review tracker, and external validation plan.",
    note: "Companion to TruthCert Pairwise Pro — no dedicated index.html, entry is 'Main screen.html'.",
    tags: ["pairwise", "ai", "meta-analysis"]
  },
  {
    name: "Living Meta",
    folder: "C:\\HTML apps\\living-meta",
    path: "./living-meta/living-meta-complete.html",
    collection: "existing",
    mode: "file",
    category: "Living Meta-Analysis",
    summary: "Self-contained living meta-analysis browser bundle with CI/container deployment scaffolding and WASM acceleration.",
    note: "Real app is living-meta-complete.html; the index.html file is a thin stub.",
    tags: ["living-review", "meta-analysis", "wasm"]
  },
  {
    name: "NMA Pro v8",
    folder: "C:\\HTML apps\\nma-pro-v2",
    path: "./nma-pro-v2/nma-pro-v8.0.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Network meta-analysis workbench v8.0 with accessibility hardening, R benchmark harness, and rapid-review workflow.",
    note: "Real app is nma-pro-v8.0.html; index.html is a thin stub.",
    tags: ["nma", "network-meta-analysis", "accessibility"]
  },
  {
    name: "NMA Dose-Response",
    folder: "C:\\HTML apps\\nma-dose-response-app",
    path: "./nma-dose-response-app/index.html",
    collection: "existing",
    mode: "file",
    category: "Network Meta-Analysis",
    summary: "Network meta-analysis for dose-response data, with 40+ novel methods and RSM editorial revisions.",
    note: "Full-featured single-file app; test files live at the app root rather than in a tests/ folder.",
    tags: ["nma", "dose-response", "novel-methods"]
  },
  {
    name: "PRISMA Flow",
    folder: "C:\\HTML apps\\prisma-flow",
    path: "./prisma-flow/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "PRISMA 2020 flow-diagram generator: enter record counts, render an SVG flow diagram, export as SVG or PNG, save state to localStorage.",
    note: "Single-file HTML, offline, deterministic output, built-in consistency checks.",
    tags: ["prisma", "systematic-review", "flow-diagram"]
  },
  {
    name: "Forest Plot Viewer",
    folder: "C:\\HTML apps\\forest-plot",
    path: "./forest-plot/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Standalone forest plot from pasted (label, estimate, SE) studies. Fixed-effect and Paule-Mandel random-effects pooling with I\u00b2 and \u03c4\u00b2.",
    note: "Single-file HTML, offline, no dependencies. SVG / PNG / JSON export.",
    tags: ["forest-plot", "meta-analysis", "pooling"]
  },
  {
    name: "Funnel Plot Explorer",
    folder: "C:\\HTML apps\\funnel-plot",
    path: "./funnel-plot/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Funnel plot with 95% and 99% pseudo-CI limits plus Egger's regression test for small-study effects (p-value via incomplete-beta t-distribution).",
    note: "Validated against scipy / statsmodels OLS. Low-k warning below 10 studies.",
    tags: ["funnel-plot", "publication-bias", "egger"]
  },
  {
    name: "RoB Traffic Light",
    folder: "C:\\HTML apps\\rob-traffic-light",
    path: "./rob-traffic-light/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Risk-of-bias traffic-light plot plus weighted summary bar, robvis-style palette. Accepts low / some / high / unclear / na ratings in several shorthand forms.",
    note: "Matrix grid + weighted-summary view, SVG / PNG / JSON export, offline.",
    tags: ["risk-of-bias", "rob2", "robvis"]
  },
  {
    name: "Heterogeneity Explorer",
    folder: "C:\\HTML apps\\heterogeneity",
    path: "./heterogeneity/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Q, I\u00b2, \u03c4\u00b2 under DL (k\u226510) / REML / PM, 95% prediction interval via t_{k-2}, Baujat diagnostic plot, and leave-one-out influence.",
    note: "Follows advanced-stats.md gates (no DL for k<10). SVG / PNG / JSON export.",
    tags: ["heterogeneity", "baujat", "prediction-interval"]
  },
  {
    name: "TSA Calculator",
    folder: "C:\\HTML apps\\tsa",
    path: "./tsa/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Trial sequential analysis: cumulative Z-score plotted against O'Brien-Fleming alpha-spending boundaries with diversity-adjusted Required Information Size.",
    note: "Auto-RIS from target effect and power, or manual in inverse-variance units.",
    tags: ["tsa", "alpha-spending", "obrien-fleming"]
  },
  {
    name: "GRADE SoF Builder",
    folder: "C:\\HTML apps\\grade-sof",
    path: "./grade-sof/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cochrane-style Summary of Findings table: outcomes, assumed and corresponding risk, relative effect, participants, four-tier GRADE certainty.",
    note: "Print-ready HTML export with standalone styles. JSON import/export.",
    tags: ["grade", "sof", "certainty-of-evidence"]
  },
  {
    name: "DTA SROC Explorer",
    folder: "C:\\HTML apps\\dta-sroc",
    path: "./dta-sroc/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Diagnostic test accuracy: per-study Se/Sp in ROC space, Moses SROC curve, and threshold-effect flag via Spearman \u03c1 between logit(Se) and logit(1-Sp).",
    note: "Applies +0.5 continuity correction only when a cell is zero (advanced-stats.md).",
    tags: ["dta", "sroc", "moses"]
  },
  {
    name: "MA Workbench",
    folder: "C:\\HTML apps\\workbench",
    path: "./workbench/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "One paste, full MA: live forest / funnel / heterogeneity / TSA previews with deep-links to dedicated apps. One-click full HTML report export.",
    note: "Writes to the shared ma-studies-v1 bus so the other apps can pull.",
    tags: ["workbench", "integrator", "bus"]
  },
  {
    name: "Meta-Regression",
    folder: "C:\\HTML apps\\meta-regression",
    path: "./meta-regression/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Random-effects meta-regression with one moderator. Paule-Mandel \u03c4\u00b2, Knapp-Hartung t(k-2) CIs with max(1, \u2026) HKSJ floor.",
    note: "Bus-aware; exports a metafor R script for PM + knha replication.",
    tags: ["meta-regression", "knapp-hartung", "moderator"]
  },
  {
    name: "Cumulative + Subgroup",
    folder: "C:\\HTML apps\\cumulative-subgroup",
    path: "./cumulative-subgroup/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Cumulative MA over study order/year; subgroup analysis with between-subgroup Q test and I\u00b2 of differences.",
    note: "Two views in one app. Reads from and writes to the shared bus.",
    tags: ["cumulative", "subgroup", "temporal"]
  },
  {
    name: "WebR Validator",
    folder: "C:\\HTML apps\\webr-validator",
    path: "./webr-validator/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Optional in-browser R (WebR) validation against metafor. Alternative paste-back path for local R. HMAC-SHA256 signed TruthCert receipts.",
    note: "WebR loads on explicit click (~30 MB download). URL configurable for self-hosting. Signing key never stored.",
    tags: ["webr", "validation", "truthcert", "hmac"]
  },
  {
    name: "Bayesian MA",
    folder: "C:\\HTML apps\\bayesian-ma",
    path: "./bayesian-ma/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Conjugate normal-normal Bayesian meta-analysis: closed-form posterior for \u03b8 given studies and a normal prior; 95% CrI, P(\u03b8<c), ROPE probability, prior-sensitivity slider.",
    note: "No MCMC, no stan, no external deps. Deterministic. Bus-aware.",
    tags: ["bayesian", "conjugate", "posterior"]
  },
  {
    name: "PRISMA Screening",
    folder: "C:\\HTML apps\\prisma-screen",
    path: "./prisma-screen/index.html",
    collection: "new",
    mode: "file",
    category: "Evidence Synthesis",
    summary: "Pre-MA citation screening: tag include/exclude/duplicate/maybe, Cohen's \u03ba for dual-reviewer agreement, PRISMA-shaped count roll-up, one-click push into the PRISMA Flow generator.",
    note: "Outputs feed directly into prisma-flow/index.html via the prisma-flow-v1 key.",
    tags: ["prisma", "screening", "kappa"]
  }
];
